### ISSUE TITLE
UI is blurry

### ISSUE THREAD

**Issue by mathew-tran** [mathew-tran/IdleCity#21]
Go through all UI in game and make them un-blurry in game

**Comment by tedescooo** [comment]
Changing the Stretch Mode to canvas_items fixes this issue

![Screenshot 2023-12-08 210715](https://github.com/mathew-tran/IdleCity/assets/5011352/917f137c-946f-4440-a080-deb28e87a17c)


![Screenshot 2023-12-08 210750](https://github.com/mathew-tran/IdleCity/assets/5011352/35ed1110-2c56-4d07-b2c4-d5643996db32)

**Comment by mathew-tran** [comment]
Awesome, thanks! 
Sorry I am a little bit new, are you unable to make a pull request to main?

**Comment by mathew-tran** [comment]
Fixed by @tedescooo !
https://github.com/mathew-tran/IdleCity/commit/0d0a59e7a5ee5217ef66ea3b0f568e1d266b1cb0
Thanks alot :)
