### ISSUE TITLE
Investigate: Game not loading for HTML5 for Linux Users using FireFox

### ISSUE THREAD

**Issue by mathew-tran** [mathew-tran/IdleCity#74]
Build: 0.0.1.18e3166e

![image](https://github.com/mathew-tran/IdleCity/assets/26263343/7c486d16-bf54-40f9-9cc6-81f7519214bc)

https://github.com/cpitclaudel/z3.wasm/blob/2dabbdff0e151cf19b2146d259101d7fe7a110b9/z3.sh#L195C1-L201C1

**Comment by mathew-tran** [comment]
Issues right now. Is I don't have linux, most likely will need to run it in a docker container and test.

My assumption right now is maybe the resources for names weren't being included or working for linux users.

**Comment by BogudanPro** [comment]
Subscribing to the thread for easier communication.

**Comment by BogudanPro** [comment]
https://github.com/cpitclaudel/cvc4.js/ also mentions BINARYEN_ASYNC_COMPILATION option causing described issue.

**Comment by mathew-tran** [comment]
hrm someone else that is using godot on linux had the same issue:
https://github.com/godotengine/godot/issues/74799

Which graphics card do you have?

**Comment by mathew-tran** [comment]
Just to give you more context. I am using Godot as the game engine and I just used the HTML5 export.

There are some docs here:
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

Curious if the browser you have supports the following?
![image](https://github.com/mathew-tran/IdleCity/assets/26263343/1ad99453-436f-4099-af2d-648710440297)

**Comment by BogudanPro** [comment]
NVIDIA Corporation GP104 [GeForce GTX 1070]
WASM does supported and enabled (see https://itch.io/post/9045967 )
WebGL 1 Driver Version	4.6.0 NVIDIA 510.60.02
WebGL 2 Driver Version	3.2.0 NVIDIA 510.60.02
SharedArrayBuffer is implemented in FF 79 (partially as of last version) and javascript.options.shared_memory	= true (enabled).
Also, it's defined on the game's pages (tested for both main page and inner frame).

**Comment by mathew-tran** [comment]
hrm. I noticed it seems you have reported this issue quite a few times on different godot games on itch.

Not sure what I can do about this. I think it is something to be fixed in a newer patch in Godot. Or it was something decidedly not supported anymore.

For now I am closing it. But thanks for raising the issue.
